# Generated by Django 5.2.3 on 2025-07-01 22:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='studio',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание студии'),
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('wrong_info', 'Неверная информация'), ('wrong_studio', 'Неверная студия'), ('wrong_genre', 'Неподходящие жанры')], max_length=20, verbose_name='Тема жалобы')),
                ('description', models.TextField(blank=True, verbose_name='Описание жалобы')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.game', verbose_name='Игра')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
