# Generated by Django 5.2.3 on 2025-07-03 00:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_studio_description_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='studio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.studio', verbose_name='Студия разработчик'),
        ),
    ]
